from enum import Enum

class OrderStatus(str, Enum):
    CRIADO = "CRIADO"
    VALIDANDO = "VALIDANDO"
    PENDENTE_PAGAMENTO = "PENDENTE_PAGAMENTO"
    PAGAMENTO_APROVADO = "PAGAMENTO_APROVADO"
    PAGAMENTO_FALHOU = "PAGAMENTO_FALHOU"
    PROCESSANDO = "PROCESSANDO"
    FINALIZADO = "FINALIZADO"
    CANCELADO = "CANCELADO"
    ERRO = "ERRO"
