from enum import Enum

# ======= ENUM Do STATUS DO PEDIDO ======= 
class OrderStatus(str, Enum):
    CRIADO = "CRIADO"
    VALIDANDO = "VALIDANDO"
    PENDENTE_PAGAMENTO = "PENDENTE_PAGAMENTO"
    PAGAMENTO_APROVADO = "PAGAMENTO_APROVADO"
    PAGAMENTO_FALHOU = "PAGAMENTO_FALHOU"
    PROCESSANDO = "PROCESSANDO"
    FINALIZADO = "FINALIZADO"
    CANCELADO = "CANCELADO"
    ERRO = "ERRO"

# ======= ENUM Da CATEGORIA DO ESTABELECIMENTO ======= 
class CategoriaEstabelecimento(str, Enum):
    RESTAURANTE = "RESTAURANTE"
    FARMACIA = "FARMACIA"
    MERCADO = "MERCADO"
    FAST_FOOD = "FAST_FOOD"
    BARZINHO = "BARZINHO"