from enum import Enum, IntEnum

# ======= ENUM Do STATUS DO PEDIDO ======= 
class OrderStatus(str, Enum):
    CRIADO = "CRIADO"
    VALIDANDO = "VALIDANDO"
    PENDENTE_PAGAMENTO = "PENDENTE_PAGAMENTO"
    PAGAMENTO_APROVADO = "PAGAMENTO_APROVADO"
    PAGAMENTO_FALHOU = "PAGAMENTO_FALHOU"
    PROCESSANDO = "PROCESSANDO"
    FINALIZADO = "FINALIZADO"
    CANCELADO = "CANCELADO"
    ERRO = "ERRO"

# ======= ENUM Da CATEGORIA DO ESTABELECIMENTO ======= 
class CategoriaEstabelecimento(str, Enum):
    RESTAURANTE = "RESTAURANTE"
    FARMACIA = "FARMACIA"
    MERCADO = "MERCADO"
    FAST_FOOD = "FAST_FOOD"
    BARZINHO = "BARZINHO"

class DiaSemana(IntEnum):
    DOMINGO = 0
    SEGUNDA = 1
    TERCA = 2
    QUARTA = 3
    QUINTA = 4
    SEXTA = 5
    SABADO = 6